[platformio]
default_envs = tbeam_regular_sx1276

[env:tbeam_regular_sx1276]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM12
monitor_port = COM12
board_build.partitions = huge_app.csv
lib_deps =
  mikalhart/TinyGPSPlus
  jgromes/RadioLib
  olikraus/U8g2
  lewisxhe/XPowersLib
  knolleary/PubSubClient
  bblanchon/ArduinoJson
build_flags =
  -DXPOWERS_CHIP_AXP192
