[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
upload_port = COM7
monitor_port = COM7
build_src_filter = +<main.cpp> -<e32_drssi_at_test.cpp>

[env:drssi_at_test]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
upload_port = COM7
monitor_port = COM7
build_src_filter = +<e32_drssi_at_test.cpp> -<main.cpp>
